controller_manager_ns: controller_manager
controller_list:
  - name: robotic_arm/robotic_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2

